apiVersion: v1
kind: Template
labels:
  demo: coolstore-microservice
metadata:
  annotations:
    description: CoolStore demo microservices application buildconfigs template
    iconClass: icon-java
    tags: microservice,jboss,spring
  name: coolstore-builds
objects:
# Coolstore Gateway
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: fis-java-openshift
  spec:
    dockerImageRepository: registry.access.redhat.com/jboss-fuse-6/fis-java-openshift
    tags:
      - name: "2.0-65"
        annotations:
          description: JBoss Fuse Integration Services 2.0 Java S2I images.
          iconClass: icon-jboss
          supports: jboss-fuse:6.3.0,java:8,xpaas:1.2
          tags: builder,jboss-fuse,java,xpaas
          version: "2.0-65"
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: coolstore-gw
  spec: {}
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: coolstore-gw
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: coolstore-gw:latest
    source:
      contextDir: coolstore-gw
      git:
        ref: ${GIT_REF}
        uri: ${GIT_URI}
      type: Git
    strategy:
      sourceStrategy:
        env:
          - name: MAVEN_ARGS
            value: package -DskipTests -Dfabric8.skip -e -B -Pearly-access-repo
          - name: MAVEN_MIRROR_URL
            value: ${MAVEN_MIRROR_URL}
        forcePull: false
        from:
          kind: ImageStreamTag
          name: fis-java-openshift:2.0-65
      type: Source
    resources:
      limits:
        cpu: 500m
        memory: "2Gi"
      requests:
        cpu: "200m"
        memory: "1Gi"
parameters:
  - description: Git source URI for application
    displayName: Git source repository
    name: GIT_URI
    required: true
    value: https://github.com/jbossdemocentral/coolstore-microservice
  - description: Git branch/tag reference
    displayName: Git branch/tag reference
    name: GIT_REF
    required: true
    value: master
  - description: Maven mirror url. If nexus is deployed locally, use nexus url (e.g. http://nexus.ci:8081/content/groups/public/)
    displayName: Maven mirror url
    name: MAVEN_MIRROR_URL
  - description: NPM mirror url. If nexus is deployed locally, use nexus url (e.g. http://nexus.ci:8081/repository/npm/)
    displayName: NPM mirror url
    name: NPM_MIRROR
  - description: Bower mirror url. If nexus is deployed locally, use nexus url (e.g. http://nexus.ci:8081/repository/bower-mirror/)
    displayName: Bower mirror url
    name: BOWER_MIRROR
  - description: Decision Server Coolstore Rules Container Spec
    name: KIE_CONTAINER_DEPLOYMENT
    required: true
    value: CoolStoreRulesContainer=com.redhat:coolstore:2.0.0